// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NA8mrFmvnPTL0Lk9VDPGztDAPrN5qag',
    appId: '1:642128417712:web:266cbb02a21d76f6cf3c75',
    messagingSenderId: '642128417712',
    projectId: 'teste-92117',
    authDomain: 'teste-92117.firebaseapp.com',
    storageBucket: 'teste-92117.firebasestorage.app',
    measurementId: 'G-4GSC1M5XJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATUjXh9h7Qfym5z8fXSDcYZNVsr7ScPak',
    appId: '1:642128417712:android:eaef35f1f3f4ce0fcf3c75',
    messagingSenderId: '642128417712',
    projectId: 'teste-92117',
    storageBucket: 'teste-92117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVjdbzW6xEfi2rwn9jJ_1j3Yzc3lecPZA',
    appId: '1:642128417712:ios:c6e2775d182eab5ccf3c75',
    messagingSenderId: '642128417712',
    projectId: 'teste-92117',
    storageBucket: 'teste-92117.firebasestorage.app',
    iosClientId: '642128417712-m7j13e7c9b6ks1qg8gtpe0qom409h94l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bike3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVjdbzW6xEfi2rwn9jJ_1j3Yzc3lecPZA',
    appId: '1:642128417712:ios:c6e2775d182eab5ccf3c75',
    messagingSenderId: '642128417712',
    projectId: 'teste-92117',
    storageBucket: 'teste-92117.firebasestorage.app',
    iosClientId: '642128417712-m7j13e7c9b6ks1qg8gtpe0qom409h94l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bike3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1NA8mrFmvnPTL0Lk9VDPGztDAPrN5qag',
    appId: '1:642128417712:web:33fbccd3485109edcf3c75',
    messagingSenderId: '642128417712',
    projectId: 'teste-92117',
    authDomain: 'teste-92117.firebaseapp.com',
    storageBucket: 'teste-92117.firebasestorage.app',
    measurementId: 'G-7XBGKXX6X1',
  );

}